### ISSUE TITLE
Array spreading is still not working correctly

### ISSUE THREAD

**Issue by ClassicOldSong** [Rich-Harris/buble#127] opened 2018-04-23 16:58 UTC
Previous issue: https://gitlab.com/Rich-Harris/buble/issues/192

Expected:
![image](https://user-images.githubusercontent.com/10512422/39141434-68d80a1a-475a-11e8-911d-272fa40b3524.png)

Actually happening:
![image](https://user-images.githubusercontent.com/10512422/39141476-83d23598-475a-11e8-9123-6ac00a94fe56.png)

[Live example](https://buble.surge.sh/#const%20aaa%20%3D%20%7B%0A%09bbb%3A%20%5B%5D%0A%7D%0A%0Aaaa.bbb.push(...%5B1%2C%202%2C%203%5D))

**Comment by pandaGao** [comment] 2018-05-03 03:44
Same Here.
For example:
```javascript
class A {
  constructor () {
    this.a = [1,2]
    this.funcA()
  }
  
  funcA () {
    console.log('Ops!')
    this.a.splice(0, 0, ...this.a)
  }
}
let a = new A()
```
will transform to
```javascript
var A = function A () {
  this.a = [1,2]
  this.funcA()
};
  
A.prototype.funcA = function funcA () {
  var ref;

  console.log('Ops!')
  (ref = this.a).splice.apply(ref, [ 0, 0 ].concat( this.a ))
};
var a = new A()
```
[Example](https://buble.surge.sh/#class%20A%20%7B%0A%20%20constructor%20()%20%7B%0A%09this.a%20%3D%20%5B1%2C2%5D%0A%09this.funcA()%0A%20%20%7D%0A%20%20%0A%20%20funcA%20()%20%7B%0A%09console.log('Ops!')%0A%09this.a.splice(0%2C%200%2C%20...this.a)%0A%20%20%7D%0A%7D%0Alet%20a%20%3D%20new%20A())


This will lead to an error `console.log(...) is not a function` which is not expected.

**Comment by fskreuz** [comment] 2018-05-08 02:45
Duplicate of https://github.com/Rich-Harris/buble/issues/87

**Closed** 2018-05-28 10:56 UTC
